# Change these first
owner: OwlTing # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: OwlNest - API
    url: https://api.owlting.com/booking/services/alive
  - name: OwlNest - Booking Engine
    url: https://booking.owlting.com/this-is-owlting
  - name: OwlJourney
    url: https://journey.owlting.com/
  - name: OwlTing Market
    url: https://www.owlting.com/market
  - name: OwlTing Experiences
    url: https://experiences.owlting.com/_nuxt/LICENSES
  - name: OwlNews
    url: https://newsapi.owlting.com/api/uuid
  - name: OwlTing NFT
    url: https://nft.owlting.com/api/tokens/69
  - name: OwlTing Portal
    url: https://www.owlting.com/portal
  - name: OwlPay Portal
    url: https://www.owlting.com/owlpay
  - name: OwlTing AML
    url: https://aml.owlpay.com/v1/health
  - name: OBS Portal
    url: https://obs.owlting.com/
  - name: OwlTing Blog
    url: https://blog.owlting.com/
  - name: OwlMap
    url: https://api.owlting.com/owlmap/health


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Owlting status page"
  introMessage: Service incidents are tracked through [Issues](https://github.com/OwlTing/upptime/issues), check progress and status report there.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/20 * * * *"
